### ISSUE TITLE
Create a "random" selector

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#17]
a new button on top right, close to the setting gear, will allow to select randomly 3 of the available music and make them start. 
Clicking it again, will stop the previous melodies played and select other random 3 songs.
use an icon in svg, from a open source / royalty free archive similar to:

![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/6b50aa53-d094-40cd-8369-9e9bd6a8d0bd)

or

![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/a96e91d8-571a-44f4-b57c-9d8f996c534c)

**Comment by daemimran** [comment]
I can help with this one.
