### ISSUE TITLE
Current active sounds and stop all button

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#19]
Right above the tiles and below the page title, show a message when at least 1 song is active:
"Sound(s) active: X. **Stop all.**"

- The bold part "Stop all." is a clickable link, which will stop all the current playing songs.
- The message when 0 songs play should not be visible
- The X in the message is showing the current playing songs.
- The font and design should be consistent with the rest of the website.

![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/aca80676-5d8d-403d-8ef2-2ec758df6388)

**Comment by spookirs** [comment]
I can take a crack at this!

**Comment by riccardobertolini** [comment]
great, thanks :)
