### ISSUE TITLE
Adding timer on top

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#3]
Would be great to have a timer on top, presenting time and date. 
Feel free to adapt the colors to something smooth and pleasant. 
The watch/date should be real time updating.

![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/ba80fbc0-a5f7-43cd-91b5-645a4912ad23)

**Comment by muzamil6** [comment]
I can help with this

**Comment by muzamil6** [comment]
are you available now

**Comment by muzamil6** [comment]
adding time and date
