### ISSUE TITLE
Use icon for volume for consistency

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#35]
![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/683bf4a6-a4b9-4398-8ddb-04db8d75a197)

The volume is currently an emoji, making it looking different from browser to browser. 
Please implement an icon from a royalty free archive with similar aspect

**Comment by hughlaufenhoft** [comment]
Can I help with this one? I think I can handle it :)

**Comment by riccardobertolini** [comment]
Sure, thanks!
