### ISSUE TITLE
Creating Setting Gear on top right

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#5]
Add a Setting Gear with a small modal, in which user can select option, coming next. 
For now, it will contain just the "about" information, same as the one available in the footer.
Those information can be hardcoded.  
The modal should appear in the middle of the page, like a small window. Both clicking outside or a "close"button in the bottom will close it, either an X on top right or a close button. 
Please take care to respect the "feel" and colors of the website

**Comment by Afaqak** [comment]
On it Sir

**Comment by riccardobertolini** [comment]
Cool thank you!
