### ISSUE TITLE
Add 3 new sounds

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#53]
-Images should be picked from the royalty free selection here https://unsplash.com/
-the image should be related to the sounds provided
-the sounds should be relaxing: thunderstorm, zen bells, city sounds etc.
-royalty free libraries for music: https://pixabay.com/music/
-no music but sounds
-sounds should not be same/similar to what already available

**Comment by DavidKozdra** [comment]
this was done correct? what would you say the max should be

**Comment by riccardobertolini** [comment]
@DavidKozdra do you mean max in terms of amount of sounds/musics? 
I'm suggesting to increase slowly (3 music at time) so I can check we're not overload the website and repository - if you meant instead weight wise, I would say music max around 3mins loop-able, and image low resolution. Let me know if you have any question :)

**Comment by riccardobertolini** [comment]
Closed by #100
