### ISSUE TITLE
Add a general player rather than HTML audio tag

### ISSUE THREAD

**Issue by shmidtelson** [riccardobertolini/lofi-music#6]
I think its good idea to use js mp3 player like this 
https://morioh.com/p/4498e950864d

**Comment by Shehzad-hash** [comment]
I can add the audio tag

**Comment by riccardobertolini** [comment]
Please be careful on the functionality currently implemented, like the Volume adjustment. Feel free to update/change it if the library or tool used require so. Thanks!

**Comment by Afaqak** [comment]
on to it
