### ISSUE TITLE
Active/Stop all bar 

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#66]
From this
![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/69ca9930-06d4-4fd3-bfa8-2172ab9ec0cd)

to this

![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/a8eb5007-e335-4d7a-92fc-2dcf8f5f41ee)

which still should appear only when sounds are active

CSS example (just for reference)
```
transition: opacity 0.3s ease 0s;
opacity: 1;
cursor: default;
display: flex;
align-items: center;
gap: 20px;
position: absolute;
bottom: 0px;
justify-content: center;
width: 100%;
z-index: 100;
background: rgba(0, 0, 0, 0.8);
color: white;
font-family: "Ubuntu", sans-serif;
```

**Comment by SubxX** [comment]
I can work on this.

**Comment by DavidKozdra** [comment]
the changes in #69 would work well here as well what do you think @riccardobertolini

**Comment by riccardobertolini** [comment]
Yes, agree with you @DavidKozdra. Let's keep this one and in case #69 is finished first we can close both - thanks!

**Comment by SubxX** [comment]
I applied my own creativity and endup with this design. Please give me your feedback should I leave it like this or create the exact design provided.
<img width="1034" alt="Screenshot 2023-07-30 at 11 26 12 PM" src="https://github.com/riccardobertolini/lofi-music/assets/51792949/a55b6520-06e6-423f-8164-5fcfd645bd9d">
I do have the given design ready in a separated branch so once I get a feedback from you I will create the appropiate PR
Thanks

**Comment by DavidKozdra** [comment]
not bad, it might be nice as some thing you can move or toggle down, If its gonna be that small I would pick a corner and an Icon as well as the text to go with the button would be a nice touch but over all really nice, react has like  a million draggable libraries

**Comment by riccardobertolini** [comment]
Looks great @SubxX! I feel this could go ahead and @DavidKozdra suggestions can come in a separate task. Thanks!

**Comment by SubxX** [comment]
Sorry for the delay guys got busy with office stuff xD
anyway I have created a PR now and yes lets create a separate task for the suggestions.

**Comment by riccardobertolini** [comment]
No worries @SubxX  thanks for your work, looks great!
