### ISSUE TITLE
Active Sounds can be negative 

### ISSUE THREAD

**Issue by DavidKozdra** [riccardobertolini/lofi-music#68]
![image](https://github.com/riccardobertolini/lofi-music/assets/45106564/220818ad-14e0-463b-9415-27f6a670ea16)

Can not easily replicate this but I have seen it about a dozen times while working on another PR 
it should not be possible though 
setting the type of the value to unsigned will help with this 

// Custom type alias for non-negative numbers
type NonNegativeNumber = number & { __nonNegative: true };

let x: NonNegativeNumber = 5;
let y: NonNegativeNumber = -10; // This will show a TypeScript error

**Comment by riccardobertolini** [comment]
Could it be due the re-rendering of react while working that on local, or does it happen in production too? 
Thank you David for your help and support 🎉

**Comment by DavidKozdra** [comment]
Have yet to see it in production but like I said hard for me to replicate I will see if it happens in production but that makes sense, I will keep testing

**Comment by riccardobertolini** [comment]
Make sense, let's keep it here, and if we can gather more info let's fill them here. Thanks again!

**Comment by DavidKozdra** [comment]
I have not seen this on prod so I will close it
