### ISSUE TITLE
Needs a Master Volume Control

### ISSUE THREAD

**Issue by saikoaizen** [riccardobertolini/lofi-music#69]
So far, we can only control volume of individual audio components but we need to create a master volume control so that the user can reduce the overall volume easily.

Currently, if the user wanted to do this, they'd have to reduce the volume of each component manually and that is just extremely unpleasant for the user.

**Comment by DavidKozdra** [comment]
I agree a good place for this would be the settings but #66 would be even better

**Comment by saikoaizen** [comment]
@DavidKozdra Yes, that would be great. I would like to work on this. Not sure if I need to be assigned first or if I can just get started?

**Comment by DavidKozdra** [comment]
sorry misclicked myself
in my experience its always good to ask etiquette wise, but feel free to start any issue that has no PR added if its not assigned

some one else is working on #66 so if you wait and we see if it will fit with the design for sure

**Comment by saikoaizen** [comment]
Yes, that makes sense. I was wondering about that too. I'll wait for them to finish the new design.

**Comment by riccardobertolini** [comment]
An option would be to take care of the #69 too with this one, and I would say if you first finish first will close both at once.
Otherwise, the overall volume can be added either below the calendar or in a place you feel would be beneficial, and then integrated in #66 - choose the one you prefer. Thanks! 👍

**Comment by saikoaizen** [comment]
@riccardobertolini Since #66 was taking a while I went ahead and made the Master Volume and a Control Bar. I wanted to ask if I should do a PR or should I change anything before that?

Here's what it looks like right now.

![Screenshot 2023-08-01 234416](https://github.com/riccardobertolini/lofi-music/assets/70025410/685011f4-4870-4065-9ee8-421a6dc549d0)

**Comment by saikoaizen** [comment]
Feature added in #79
