### ISSUE TITLE
Current  background colors Highlight 

### ISSUE THREAD

**Issue by DavidKozdra** [riccardobertolini/lofi-music#71]
would be helpful to add an active style to the current color 
![image](https://github.com/riccardobertolini/lofi-music/assets/45106564/d7defb07-bf60-458f-9ec7-5e02614410f9)

**Comment by riccardobertolini** [comment]
Great addition, thanks for reporting it

**Comment by DavidKozdra** [comment]
@riccardobertolini I will do this soon, wanted to know what kind of design you would want, it could be a highlight on the background or a bold black border, or a line

**Comment by riccardobertolini** [comment]
feel free to propose something, with the current design could be the hover state active or something else 😃

**Comment by DavidKozdra** [comment]
Pr for this added

**Comment by riccardobertolini** [comment]
Great PR, just merged. Closing the task - thanks!
