### ISSUE TITLE
Redundant Calendar Feature

### ISSUE THREAD

**Issue by saikoaizen** [riccardobertolini/lofi-music#72]
There's a date on the website, If I click on the date a calendar pops up and I can't do anything because it doesn't read user input.
This feature seems redundant for now because it's not really doing anything and I don't see the purpose of this in a Lofi-Music website.

I could be missing something here so please correct me if I'm wrong

![calendar](https://github.com/riccardobertolini/lofi-music/assets/70025410/df2ec96b-831f-4afa-ae1e-e065a5a1003d)
![date](https://github.com/riccardobertolini/lofi-music/assets/70025410/0e17db98-4757-45da-a4aa-7632074fccb2)

**Comment by riccardobertolini** [comment]
Good point, thanks for raising this - the idea was to add a series of small helpful tools, like note/todo list and a calendar, pomodoro timer - however it's indeed redundant as it's done right now. We can either choose to remove the calendar option and leave the date or remove both.

**Comment by saikoaizen** [comment]
@riccardobertolini That makes sense. I too think that it's better to remove both of them now as an incomplete feature in production doesn't look good. We can add them as complete features later on. If that's okay with you, please assign this to me I can remove them.

**Comment by riccardobertolini** [comment]
Sure, thanks for helping with this!
