### ISSUE TITLE
Add Full Screen option 

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#8]
On top right, create a new row where the button for full screen will be added. 
Clicking that, the browser will go to full screen and the icon will change. 
If I click it again, then back to windowed version.

Fell free to choose a free library or icons (all royalty free) for this project.

**Comment by asad-makhdoom** [comment]
I can help with this one. Please assign this to me

**Comment by riccardobertolini** [comment]
Sure, thank you :+1:
