### ISSUE TITLE
Create "mood" selection

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#83]
A new icon (some inspiration here https://www.flaticon.com/free-icons/mood) will open a modal (or show a select under the calendar, the best visual option) that will allow to select some mood combination of sounds. 
Example: 
- Relax -> activate birds and meditation sounds
- Reflective -> piano + rain sounds
- Morning Coffee -> Sea + harp
Many more to be add in the future, so the system should be flexible for future implementations

**Comment by egorii87** [comment]
hello! can I tackle this issue?

**Comment by egorii87** [comment]
hello! can I tackle this issue?

**Comment by riccardobertolini** [comment]
Sure, let me know if you have any question! Assigned to you

**Comment by DavidKozdra** [comment]
@egorii87 how's it going?

**Comment by egorii87** [comment]
@DavidKozdra I solved this issue, but probably the author wants more solutions if he didn't close the topic

**Comment by riccardobertolini** [comment]
Apologies, the task has been indeed completed. Thanks for your hard work - closing it right now
