### ISSUE TITLE
Once changed color, cannot revert to Purple pink 

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#96]
Just noticed that if you click back on the default color, Purple Pink from the setting modal, does not change it.
Probably is missing the reference somewhere in the color list - not sure. Opening this so we can investigate

![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/7f408970-3aab-4bc7-9aa2-01bb83e4f2da)

**Comment by DavidKozdra** [comment]
I noticed this as well sorry for the bug, not sure what is causing it 

  useEffect(() => {
    if (selectedColor) {
      document.documentElement.style.backgroundColor = selectedColor.fallback
      document.documentElement.style.backgroundImage = selectedColor.gradient
    }else {
      setSelectedColor(colors[0])
    }
  }, [selectedColor])
  
  its not null and logs 
  
  {name: 'purple-pink', gradient: 'linear-gradient( to right, #000 0%, #44107a 55%, #ff1361 66%, #44107a 76%, #000 100% );', fallback: '#ff1361'}

The only thing I can think is the color is longer than the others and might be in a different format

**Comment by riccardobertolini** [comment]
No worries! :) I can help figure it out, thanks for your hard work!

**Comment by kristenking** [comment]
Looks like @saikoaizen fixed it. All works as expected now.

**Comment by riccardobertolini** [comment]
#100 fixed this as well! :)
