### ISSUE TITLE
Center the volume and adjust Stop all button

### ISSUE THREAD

**Issue by riccardobertolini** [riccardobertolini/lofi-music#97]
![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/7459d79e-d68e-47ef-afcc-26e7d95b683d)

On mobile the stop all is a bit too small (Galaxy s20 on Firefox debug)

![image](https://github.com/riccardobertolini/lofi-music/assets/29015454/17e3ee37-5750-4dc6-965b-ac8bf3110eb5)

* center the volume horizontally
* make slightly larger the stop all on mobile

**Comment by kristenking** [comment]
Hi @riccardobertolini! Could I work on this issue please?

**Comment by riccardobertolini** [comment]
Sure thing, assigning to you this task. Let me know if you have any question!

**Comment by kristenking** [comment]
Thank you @riccardobertolini !
